version: '3'

services:
  web:
    container_name: nginx
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "html-vol:/usr/share/nginx/html"
  
  db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file: common.env

volumes: 
  html-vol: