version: '3'

services:
  web:
    container_name: nginx
    mem_limit: 200m
    cpuset: "0"
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "html-vol:/usr/share/nginx/html"
    networks:
      - net-test
  
  db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file: common.env
    volumes:
      - "mysql-vol:/var/lib/mysql"
    networks:
      - net-test

volumes: 
  html-vol:
  mysql-vol:

networks: 
  net-test: